### ISSUE TITLE
use README.md as index page instead of index.md

### ISSUE THREAD

**Issue by bufferoverflow** [tomchristie/mkdocs#321]
It would be great to have a config option index_page or similar to change the index page to e.g. README.md instead of index.md.

**Comment by d0ugal** [comment]
So, I guess you want this so that GitHub renders the markdown when browsing the code? i.e. if I went to https://github.com/tomchristie/mkdocs/tree/master/docs I'd see the index rendered if it were named README?

That would be nice, I can see it being useful. However, in an effort to avoid adding more configuration options we don't want to do that. For now I'd suggest duplicating the index, which I know is a hack. It may be that if/when we adopt a new pages config (like this maybe: https://github.com/tomchristie/mkdocs/issues/6#issuecomment-68661197) we solve this at the same time.

**Comment by maxlinc** [comment]
I came looking for this as well. I spotted mkdocs in the [readthedocs docs](https://docs.readthedocs.org/en/latest/builds.html#mkdocs) and then was a little surprised that when I ran the preview locally it didn't match how it would behave on readthedocs.

The main difference is:
> If you have a README.md, it will be transformed into an index.md automatically.

That doesn't seem like something that should need a configuration option, since it could just be a simple fallback. Use docs/index.md if it exists, or use README.md if it doesn't. The only issue I see is that relative links in the README need to be adjusted. Not sure if readthedocs does that already...

**Comment by d0ugal** [comment]
We already re-write URL's where needed. Nothing extra would be required here as the README.md would be in the same directory as where the index.md file would be.

**Comment by d0ugal** [comment]
@maxlinc What is different about how it works on ReadTheDocs? Do they do something with README files?

**Comment by maxlinc** [comment]
It sounds like it, but I haven't tried to test it. I did try grepping their code to see where this might be happening, but didn't find anything. Then again I'm not a python developer or familliar with readthedocs.

@ericholscher - Is this definitely a feature or could it have been a copy/paste mistake when you updated the docs in [this commit](https://github.com/rtfd/readthedocs.org/commit/e3888d10c996d73eade3538fcc65d30b2a46429c)? I noticed it basically says the same thing for mkdocs as sphinx, just replacing `readme.rst` with `readme.md`.

**Comment by d0ugal** [comment]
It looks like they have [some magic that might do it](https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/base.py#L89-L103), specifically [line 100](https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/base.py#L100) which just makes a copy of the README to the index.

**Comment by maxlinc** [comment]
Ok, so it looks like it happens within `docs_dir`, which matches up with what you were saying but isn't quite what I had envisioned.

> We already re-write URL's where needed. Nothing extra would be required here as the README.md would be in the same directory as where the index.md file would be.

So that makes sense, but I'd envisioned something slightly different. I was thinking it would copy README.md from the root of the repo, or equivalently README.md from the directory that contains mkdocs.yml. So I thought it would copy README.md to docs/index.md (instead of docs/README.md to docs/index.md).

That's when you get errors with relative links:
```
Building documentation to directory: site
Directory site contains stale files. Use --clean to remove them.
Traceback (most recent call last):
  File "/Users/Thoughtworker/Envs/polytrix/bin/mkdocs", line 9, in <module>
    load_entry_point('mkdocs==0.11.1', 'console_scripts', 'mkdocs')()
  File "/Users/Thoughtworker/Envs/polytrix/lib/python2.7/site-packages/mkdocs/main.py", line 60, in run_main
    main(cmd, args=sys.argv[2:], options=dict(opts))
  File "/Users/Thoughtworker/Envs/polytrix/lib/python2.7/site-packages/mkdocs/main.py", line 36, in main
    build(config, clean_site_dir=clean_site_dir)
  File "/Users/Thoughtworker/Envs/polytrix/lib/python2.7/site-packages/mkdocs/build.py", line 266, in build
    build_pages(config)
  File "/Users/Thoughtworker/Envs/polytrix/lib/python2.7/site-packages/mkdocs/build.py", line 214, in build_pages
    html_content = post_process_html(html_content, site_navigation)
  File "/Users/Thoughtworker/Envs/polytrix/lib/python2.7/site-packages/mkdocs/build.py", line 82, in post_process_html
    html_content = re.sub(r'a href="([^"]*)"', anchor_sub, html_content)
  File "/Users/Thoughtworker/Envs/polytrix/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/Users/Thoughtworker/Envs/polytrix/lib/python2.7/site-packages/mkdocs/build.py", line 39, in __call__
    assert False, msg % (source_file, target_file)
AssertionError: The page "index.md" contained a hyperlink to "docs/configuration.md" which is not listed in the "pages" configuration.
```

**Comment by d0ugal** [comment]
Oh, I see. I'm not sure I like the idea of copying files in from another location, that adds quite a bit of extra complexity. I don't think ReadTheDocs does this either. Doing this would require another configuration option, as we can't assume the README one level up from the docs_dir is something we can touch. Then there is the re-writing of paths that you mentioned, which would be a different case than what we do in other files AFAICT.

So, yeah, I'm -1 on that idea.

**Comment by maxlinc** [comment]
Yeah, now that I see that's not what readthedocs meant I also agree it isn't worth the trouble at this point. If readthedocs already had working code for README.md -> docs/index.md it might make sense to port it to this project, but that isn't the case.

I guess I'll have to start using short READMEs that just link to docs/README.md rather than putting an overview or getting started guide in the readme.

The docs/README.md feature would still be convenient so the local preview server would match how it is handled by both GitHub and readthedocs.
