### ISSUE TITLE
Link YAML configuration files from different projects. 

### ISSUE THREAD

**Issue by BuzzVII** [tomchristie/mkdocs#340]
# Summary
Two projects could be developed seperately and contain seperate mkdocs.yml files and thier own markdown docs. If combined documentation needed to be produced this would require moving around the md files/sym linking/horrible relative path names (../../../project/docs etc) and a new configuration file created that has all the pages. If a projects documentation is changed, this will need to be maintained in two seperate places. I nicer solution would be to have a method for linking projects in the configuration files. This would allow for each project to have standalone functioning documentation while also facilitate merging documentation from projects.

# Example Solution
I've implemented some code to demonstrate to some degree the idea. 
[Test code diffs](https://github.com/BuzzVII/mkdocs/commit/b72f335481affc40e2caa35e6ee4d2514149cc41)

The docs folder for each link would then be symlinked or mounted into the main docs folder to preserve their paths. Another method could be to include the other repository base dir and then it looks in that projects directories without the need for symlinks. I haven't really thought fully about the implementation details. If you think it is a feature worth implementing I can certainly help with some discussion on structure and it's implementation.

**Comment by d0ugal** [comment]
-1, I think this is a very specific use case that we don't want to support in MkDocs. I'd suggest that two projects that are as closely bound as the ones you describe should just merge the documentation into one - this will be a painful piece of work but will be much easier for everyone in the long run.

**Comment by c42f** [comment]
We're not talking about two projects which can be merged here - it's a large number of projects which each has more or less self-contained documentation.  (These are internal projects where not all users even have access to all source code.)

However, we'd like to tie the documentation together somehow.  Maybe the solution is just to make an external table of contents and index the documentation independently of mkdocs.  Seems a bit clunky but might work out.

**Comment by d0ugal** [comment]
The approach you describe has a number of issues and I think it would quickly become messy to implement, use and support.

- I can't see how MkDocs would do more than generate a linking page. If it tried to generate a full nav for all the projects that would probably look horrific soon.
- How would a user build the linked documentation if they can't access all the repos?
- Since the docs need to work together and individually, writing them would be difficult as the prose would need to take into account both viewpoints.

The only advantage I can think of would be for integrated search (coming at some point with #222). However, it wouldn't be hard to do something custom that loads all the indexes for each sub project.

**Comment by c42f** [comment]
Ok, thanks for the input, it's early days for the docs project in question.  We'll try to come up with something sane and see if any parts of it can be integrated back later.
