### ISSUE TITLE
json help option undocumented?

### ISSUE THREAD

**Issue by thinkhuman** [tomchristie/mkdocs#353]
I'm seeing a command -line option for the mkdocs command called "json". I don't see it documented anywhere. Is it unimplemented? Undocumented?

**Comment by walchko** [comment]
Well, any help would be useful ... this output isn't very useful:

```bash
$ mkdocs help
mkdocs [help|new|build|serve|gh-deploy|json] {options}
```

**Comment by d0ugal** [comment]
Yeah, so, it really isn't useful, I agree. This comes under #259, we need to rework the command line to add help output etc.

The JSON command works and is implemented. Rather than outputting html files in the build directory it creates .json files containing the contents of the page. It's a slightly odd addition, and may change before we hit 1.0 but it was added for ReadTheDocs (so they can more easily index MkDocs projects in their search backend).

**Comment by thinkhuman** [comment]
Thanks @d0ugal. Actually, this is a feature I'm excited about--the ability to output json, to (for example) create endpoints for devs to (contextually) link to help content. Hope it stays in and gets some attention.

**Comment by d0ugal** [comment]
@thinkhuman I don't understand your use case, can you explain it further? What attention do you think it needs?

The only use case we have is for search and since we are adding search to MkDocs (slowly in #222) we would have two JSON formats. The plan/idea was to combine these and potentially drop the json command.
