### ISSUE TITLE
pdf export?

### ISSUE THREAD

**Issue by logemann** [tomchristie/mkdocs#374]
Hi,

1st of all. NICE project. Love it.

Is there any way to get a PDF out of it?

Marc

**Comment by d0ugal** [comment]
Thanks!

We don't have anything for PDFS exports at the moment.

**Comment by pcastellazzi** [comment]
I would suggest to use CSS Media Types (```@media print { /* ... /* }```) and something like http://wkhtmltopdf.org as a workaround.

**Comment by d0ugal** [comment]
It would be easy to achieve something like this with a custom theme.

**Comment by jgrassler** [comment]
I tried wkhtmltopdf and plenty of somethings like it (weasyprint, htmldoc, Calibre's ebook-convert). I found all of them less than satisfactory:

* wkhtml2pdf and weasyprint couldn't cope with multiple HTML files, at least without specially patched QT libraries
* htmldoc had various small conversion issues such as omitting chapter headings 
* ebook-convert is a headless tool that claims to require an X server for PDF conversion - that ruled it out for our documentation machine

In a nutshell, HTML to PDF conversation is still a shaky sort of thing. Since that still holds true I chose an alternative route and hacked up a bunch of precprocessors to convert mkdocs flavored Markdown to one long document that is digestible by pandoc - which can do PDF conversion just fine. These preprocessors are a bit messy right now (some are Python, some are Ruby and others still are sed invocations in a Makefile). I can convert all that stuff into Python classes and a few extra command line options and submit the whole thing as a pull request. Would you be interested in that?

**Comment by trel** [comment]
Yes, please.

**Comment by d0ugal** [comment]
While I understand there is desire for something like this, I don't share it. @jgrassler, I would be interested in seeing how much code you would need to change to make it happen. If it is minor I could be tempted. However, I am not totally convinced (for a number of reasons) so I don't want you to invest a ton of time into it.

This is probably something that can be done as a plugin (when that becomes a realistic option #206). However, I am aware that doesn't help now.

An alternative would be to put this code into a package that people run after a `mkdocs build` and then they can use it that way.

**Comment by jgrassler** [comment]
It is definitely not minor. While I would not have to change much in mkdocs itself (only add a --pandoc option or something like that to the command line tool), I would have to add a whole lot of mostly independent code, though. If that works for you I'm happy to submit a pull request, but if it's too much (entirely understandable) I'd be fine with turning it into a separate package.

**Comment by d0ugal** [comment]
Let's go for a separate package for now, it is much easier to later pull things into MkDocs than it is to remove them :) Please keep us posted on this issue with how you get on, I would like to see how it works.

**Comment by jgrassler** [comment]
Alright, I'll pursue that course then :-)

For now, you will find the current mess of scripts here: http://github.com/jgrassler/mkdocs-pandoc

**Comment by jgrassler** [comment]
OK, the Python modulle is finished.

It's installable through pip:

```
pip install mkdocs-pandoc
```

It comes with a command line converter (`mkdocs2pandoc`).

**Comment by Breakthrough** [comment]
I've been wondering about this for some time myself, so awesome work @jgrassler (much appreciated).  The Pandoc approach seems to be the way to go for the time being, looking forward to testing the new module out :)

**Comment by mkoertgen** [comment]
Followed usage to install the stable version. When calling `mkdocs2pandoc` i get an error relating to markdown-extensions

    Traceback (most recent call last):
      File "C:\python\Scripts\mkdocs2pandoc-script.py", line 9, in <module>
        load_entry_point('mkdocs-pandoc==0.2.3', 'console_scripts', 'mkdocs2pandoc')
    ()
      File "C:\python\lib\site-packages\mkdocs_pandoc\cli\mkdocs2pandoc.py", line 69
    , in main
        encoding=args.encoding,
      File "C:\python\lib\site-packages\mkdocs_pandoc\pandoc_converter.py", line 52,
     in __init__
        for ext in self.config['markdown_extensions']:
    KeyError: 'markdown_extensions'

I am not quite sure what this means.

**Comment by d0ugal** [comment]
@mkoertgen Please report the issue against the mkdocs2pandoc repo: https://github.com/jgrassler/mkdocs-pandoc

**Comment by gchiappe** [comment]
@mkoertgen mkdocs2pandoc requires pandoc, and pandoc to generate pdfs requires latex that is a 1.8+ GB download and install... not a good solution

**Comment by noraj1337** [comment]
There is also [`mkdocs-combine`](https://twardoch.github.io/mkdocs-combine/) that do the same as [`mkdocs-pandoc`](https://github.com/jgrassler/mkdocs-pandoc).

**Comment by noraj1337** [comment]
It's also possible to use phantomjs as [reveal-md](https://github.com/webpro/reveal-md) do convert their markdown slides to PDF.

Or [mkpdf](https://github.com/FrontendMatter/mkpdf) that marked and wkhtmltopdf.

Or [markdown-pdf](https://github.com/alanshaw/markdown-pdf)

Etc... there are a lot of ready to use ways to do it.

**Comment by waylan** [comment]
> But if it is possible to convert markdown slides to PDF why won't it be possible to convert mkdoc to PDF ?

I imagine it is possible. It's just that no one has built the tool yet. Those of us who maintain MkDocs, do so as volunteers in our spare time. Personally, I have no need for converting to PDF, so I have no reason/incentive to build that tool. This issue has been closed as we have no plans to build support for such a feature directly into MkDocs.

I expect that if someone were to build a easy-to-use third-party tool, it would be popular. The Plugin API is now available in master (see #1223) and will be included in the next release, so that should make it easier to implement a third-party solution. If there is anything we can do to make it easier, let us know by filing an issue or, even better, a PR which includes the needed changes.

**Comment by matthewblain** [comment]
Commenting on an old bug: The recent mkdocs-pdf-export-plugin seems to do the trick.

**Comment by mkoertgen** [comment]
@matthewblain This should be it: https://github.com/zhaoterryy/mkdocs-pdf-export-plugin yes? Thanks will try it out.

**Comment by jwaschkau** [comment]
I get good looking results with this plugin https://github.com/comwes/mkpdfs-mkdocs-plugin
